// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: krayt.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GuestAgent_Hello_FullMethodName            = "/krayt.v1.GuestAgent/Hello"
	GuestAgent_QueryImageBlobs_FullMethodName  = "/krayt.v1.GuestAgent/QueryImageBlobs"
	GuestAgent_PushImage_FullMethodName        = "/krayt.v1.GuestAgent/PushImage"
	GuestAgent_PushCode_FullMethodName         = "/krayt.v1.GuestAgent/PushCode"
	GuestAgent_PushTask_FullMethodName         = "/krayt.v1.GuestAgent/PushTask"
	GuestAgent_PushSecrets_FullMethodName      = "/krayt.v1.GuestAgent/PushSecrets"
	GuestAgent_SetNetworkPolicy_FullMethodName = "/krayt.v1.GuestAgent/SetNetworkPolicy"
	GuestAgent_Start_FullMethodName            = "/krayt.v1.GuestAgent/Start"
	GuestAgent_CollectArtifacts_FullMethodName = "/krayt.v1.GuestAgent/CollectArtifacts"
	GuestAgent_Answer_FullMethodName           = "/krayt.v1.GuestAgent/Answer"
	GuestAgent_Shutdown_FullMethodName         = "/krayt.v1.GuestAgent/Shutdown"
)

// GuestAgentClient is the client API for GuestAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuestAgentClient interface {
	// Handshake + version negotiation.
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	// Incremental image transfer (§6.11): host asks which blobs the guest already has,
	// then streams only the missing ones.
	QueryImageBlobs(ctx context.Context, in *BlobQuery, opts ...grpc.CallOption) (*BlobPresence, error)
	PushImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, Ack], error)
	PushCode(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, Ack], error)
	PushTask(ctx context.Context, in *TaskSpec, opts ...grpc.CallOption) (*Ack, error)
	PushSecrets(ctx context.Context, in *SecretsBundle, opts ...grpc.CallOption) (*Ack, error)
	SetNetworkPolicy(ctx context.Context, in *NetworkPolicy, opts ...grpc.CallOption) (*Ack, error)
	// Start the container and stream events until it exits. The final RunEvent carries
	// the terminal Status (exit code); the stream then closes.
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error)
	CollectArtifacts(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error)
	Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*Ack, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*Ack, error)
}

type guestAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewGuestAgentClient(cc grpc.ClientConnInterface) GuestAgentClient {
	return &guestAgentClient{cc}
}

func (c *guestAgentClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, GuestAgent_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestAgentClient) QueryImageBlobs(ctx context.Context, in *BlobQuery, opts ...grpc.CallOption) (*BlobPresence, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlobPresence)
	err := c.cc.Invoke(ctx, GuestAgent_QueryImageBlobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestAgentClient) PushImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GuestAgent_ServiceDesc.Streams[0], GuestAgent_PushImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Chunk, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_PushImageClient = grpc.ClientStreamingClient[Chunk, Ack]

func (c *guestAgentClient) PushCode(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GuestAgent_ServiceDesc.Streams[1], GuestAgent_PushCode_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Chunk, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_PushCodeClient = grpc.ClientStreamingClient[Chunk, Ack]

func (c *guestAgentClient) PushTask(ctx context.Context, in *TaskSpec, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, GuestAgent_PushTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestAgentClient) PushSecrets(ctx context.Context, in *SecretsBundle, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, GuestAgent_PushSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestAgentClient) SetNetworkPolicy(ctx context.Context, in *NetworkPolicy, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, GuestAgent_SetNetworkPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestAgentClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GuestAgent_ServiceDesc.Streams[2], GuestAgent_Start_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartRequest, RunEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_StartClient = grpc.ServerStreamingClient[RunEvent]

func (c *guestAgentClient) CollectArtifacts(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GuestAgent_ServiceDesc.Streams[3], GuestAgent_CollectArtifacts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CollectRequest, Chunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_CollectArtifactsClient = grpc.ServerStreamingClient[Chunk]

func (c *guestAgentClient) Answer(ctx context.Context, in *AnswerRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, GuestAgent_Answer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestAgentClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, GuestAgent_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuestAgentServer is the server API for GuestAgent service.
// All implementations must embed UnimplementedGuestAgentServer
// for forward compatibility.
type GuestAgentServer interface {
	// Handshake + version negotiation.
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	// Incremental image transfer (§6.11): host asks which blobs the guest already has,
	// then streams only the missing ones.
	QueryImageBlobs(context.Context, *BlobQuery) (*BlobPresence, error)
	PushImage(grpc.ClientStreamingServer[Chunk, Ack]) error
	PushCode(grpc.ClientStreamingServer[Chunk, Ack]) error
	PushTask(context.Context, *TaskSpec) (*Ack, error)
	PushSecrets(context.Context, *SecretsBundle) (*Ack, error)
	SetNetworkPolicy(context.Context, *NetworkPolicy) (*Ack, error)
	// Start the container and stream events until it exits. The final RunEvent carries
	// the terminal Status (exit code); the stream then closes.
	Start(*StartRequest, grpc.ServerStreamingServer[RunEvent]) error
	CollectArtifacts(*CollectRequest, grpc.ServerStreamingServer[Chunk]) error
	Answer(context.Context, *AnswerRequest) (*Ack, error)
	Shutdown(context.Context, *ShutdownRequest) (*Ack, error)
	mustEmbedUnimplementedGuestAgentServer()
}

// UnimplementedGuestAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuestAgentServer struct{}

func (UnimplementedGuestAgentServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedGuestAgentServer) QueryImageBlobs(context.Context, *BlobQuery) (*BlobPresence, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryImageBlobs not implemented")
}
func (UnimplementedGuestAgentServer) PushImage(grpc.ClientStreamingServer[Chunk, Ack]) error {
	return status.Error(codes.Unimplemented, "method PushImage not implemented")
}
func (UnimplementedGuestAgentServer) PushCode(grpc.ClientStreamingServer[Chunk, Ack]) error {
	return status.Error(codes.Unimplemented, "method PushCode not implemented")
}
func (UnimplementedGuestAgentServer) PushTask(context.Context, *TaskSpec) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method PushTask not implemented")
}
func (UnimplementedGuestAgentServer) PushSecrets(context.Context, *SecretsBundle) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method PushSecrets not implemented")
}
func (UnimplementedGuestAgentServer) SetNetworkPolicy(context.Context, *NetworkPolicy) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNetworkPolicy not implemented")
}
func (UnimplementedGuestAgentServer) Start(*StartRequest, grpc.ServerStreamingServer[RunEvent]) error {
	return status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedGuestAgentServer) CollectArtifacts(*CollectRequest, grpc.ServerStreamingServer[Chunk]) error {
	return status.Error(codes.Unimplemented, "method CollectArtifacts not implemented")
}
func (UnimplementedGuestAgentServer) Answer(context.Context, *AnswerRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Answer not implemented")
}
func (UnimplementedGuestAgentServer) Shutdown(context.Context, *ShutdownRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedGuestAgentServer) mustEmbedUnimplementedGuestAgentServer() {}
func (UnimplementedGuestAgentServer) testEmbeddedByValue()                    {}

// UnsafeGuestAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuestAgentServer will
// result in compilation errors.
type UnsafeGuestAgentServer interface {
	mustEmbedUnimplementedGuestAgentServer()
}

func RegisterGuestAgentServer(s grpc.ServiceRegistrar, srv GuestAgentServer) {
	// If the following call panics, it indicates UnimplementedGuestAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GuestAgent_ServiceDesc, srv)
}

func _GuestAgent_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestAgent_QueryImageBlobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlobQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).QueryImageBlobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_QueryImageBlobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).QueryImageBlobs(ctx, req.(*BlobQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestAgent_PushImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GuestAgentServer).PushImage(&grpc.GenericServerStream[Chunk, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_PushImageServer = grpc.ClientStreamingServer[Chunk, Ack]

func _GuestAgent_PushCode_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GuestAgentServer).PushCode(&grpc.GenericServerStream[Chunk, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_PushCodeServer = grpc.ClientStreamingServer[Chunk, Ack]

func _GuestAgent_PushTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).PushTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_PushTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).PushTask(ctx, req.(*TaskSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestAgent_PushSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretsBundle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).PushSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_PushSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).PushSecrets(ctx, req.(*SecretsBundle))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestAgent_SetNetworkPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkPolicy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).SetNetworkPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_SetNetworkPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).SetNetworkPolicy(ctx, req.(*NetworkPolicy))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestAgent_Start_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GuestAgentServer).Start(m, &grpc.GenericServerStream[StartRequest, RunEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_StartServer = grpc.ServerStreamingServer[RunEvent]

func _GuestAgent_CollectArtifacts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CollectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GuestAgentServer).CollectArtifacts(m, &grpc.GenericServerStream[CollectRequest, Chunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_CollectArtifactsServer = grpc.ServerStreamingServer[Chunk]

func _GuestAgent_Answer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).Answer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_Answer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).Answer(ctx, req.(*AnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestAgent_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuestAgent_ServiceDesc is the grpc.ServiceDesc for GuestAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuestAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "krayt.v1.GuestAgent",
	HandlerType: (*GuestAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _GuestAgent_Hello_Handler,
		},
		{
			MethodName: "QueryImageBlobs",
			Handler:    _GuestAgent_QueryImageBlobs_Handler,
		},
		{
			MethodName: "PushTask",
			Handler:    _GuestAgent_PushTask_Handler,
		},
		{
			MethodName: "PushSecrets",
			Handler:    _GuestAgent_PushSecrets_Handler,
		},
		{
			MethodName: "SetNetworkPolicy",
			Handler:    _GuestAgent_SetNetworkPolicy_Handler,
		},
		{
			MethodName: "Answer",
			Handler:    _GuestAgent_Answer_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _GuestAgent_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushImage",
			Handler:       _GuestAgent_PushImage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PushCode",
			Handler:       _GuestAgent_PushCode_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Start",
			Handler:       _GuestAgent_Start_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CollectArtifacts",
			Handler:       _GuestAgent_CollectArtifacts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "krayt.proto",
}
