// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: krayt.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkPolicy_Mode int32

const (
	NetworkPolicy_ALLOWLIST NetworkPolicy_Mode = 0
	NetworkPolicy_FULL      NetworkPolicy_Mode = 1
	NetworkPolicy_NONE      NetworkPolicy_Mode = 2
)

// Enum value maps for NetworkPolicy_Mode.
var (
	NetworkPolicy_Mode_name = map[int32]string{
		0: "ALLOWLIST",
		1: "FULL",
		2: "NONE",
	}
	NetworkPolicy_Mode_value = map[string]int32{
		"ALLOWLIST": 0,
		"FULL":      1,
		"NONE":      2,
	}
)

func (x NetworkPolicy_Mode) Enum() *NetworkPolicy_Mode {
	p := new(NetworkPolicy_Mode)
	*p = x
	return p
}

func (x NetworkPolicy_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkPolicy_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_krayt_proto_enumTypes[0].Descriptor()
}

func (NetworkPolicy_Mode) Type() protoreflect.EnumType {
	return &file_krayt_proto_enumTypes[0]
}

func (x NetworkPolicy_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkPolicy_Mode.Descriptor instead.
func (NetworkPolicy_Mode) EnumDescriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{7, 0}
}

type LogLine_Stream int32

const (
	LogLine_STDOUT LogLine_Stream = 0
	LogLine_STDERR LogLine_Stream = 1
)

// Enum value maps for LogLine_Stream.
var (
	LogLine_Stream_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
	}
	LogLine_Stream_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
	}
)

func (x LogLine_Stream) Enum() *LogLine_Stream {
	p := new(LogLine_Stream)
	*p = x
	return p
}

func (x LogLine_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLine_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_krayt_proto_enumTypes[1].Descriptor()
}

func (LogLine_Stream) Type() protoreflect.EnumType {
	return &file_krayt_proto_enumTypes[1]
}

func (x LogLine_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLine_Stream.Descriptor instead.
func (LogLine_Stream) EnumDescriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{10, 0}
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion string                 `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_krayt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type HelloResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion      string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ContainerdVersion string                 `protobuf:"bytes,2,opt,name=containerd_version,json=containerdVersion,proto3" json:"containerd_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_krayt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HelloResponse) GetContainerdVersion() string {
	if x != nil {
		return x.ContainerdVersion
	}
	return ""
}

type BlobQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digests       []string               `protobuf:"bytes,1,rep,name=digests,proto3" json:"digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobQuery) Reset() {
	*x = BlobQuery{}
	mi := &file_krayt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobQuery) ProtoMessage() {}

func (x *BlobQuery) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobQuery.ProtoReflect.Descriptor instead.
func (*BlobQuery) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{2}
}

func (x *BlobQuery) GetDigests() []string {
	if x != nil {
		return x.Digests
	}
	return nil
}

type BlobPresence struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MissingDigests []string               `protobuf:"bytes,1,rep,name=missing_digests,json=missingDigests,proto3" json:"missing_digests,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlobPresence) Reset() {
	*x = BlobPresence{}
	mi := &file_krayt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobPresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobPresence) ProtoMessage() {}

func (x *BlobPresence) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobPresence.ProtoReflect.Descriptor instead.
func (*BlobPresence) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{3}
}

func (x *BlobPresence) GetMissingDigests() []string {
	if x != nil {
		return x.MissingDigests
	}
	return nil
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Last          bool                   `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_krayt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{4}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Chunk) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *Chunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

// TaskSpec carries the non-secret task config to the guest (§6.10/§8.1). The container-policy
// fields (3–5) let the host opt into least-privilege overrides the guest applies when it builds
// the OCI spec: caps default to drop-all (empty add_capabilities), seccomp defaults to the
// containerd profile, and the rootfs is writable unless readonly_rootfs is set.
type TaskSpec struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Prompt            []byte                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Env               map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // env = non-secret
	AddCapabilities   []string               `protobuf:"bytes,3,rep,name=add_capabilities,json=addCapabilities,proto3" json:"add_capabilities,omitempty"`                            // opt-in caps, CAP_-prefixed; empty = drop all
	SeccompUnconfined bool                   `protobuf:"varint,4,opt,name=seccomp_unconfined,json=seccompUnconfined,proto3" json:"seccomp_unconfined,omitempty"`                     // opt-out of the default seccomp profile
	ReadonlyRootfs    bool                   `protobuf:"varint,5,opt,name=readonly_rootfs,json=readonlyRootfs,proto3" json:"readonly_rootfs,omitempty"`                              // opt-in read-only rootfs (default false)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskSpec) Reset() {
	*x = TaskSpec{}
	mi := &file_krayt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSpec) ProtoMessage() {}

func (x *TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSpec.ProtoReflect.Descriptor instead.
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{5}
}

func (x *TaskSpec) GetPrompt() []byte {
	if x != nil {
		return x.Prompt
	}
	return nil
}

func (x *TaskSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *TaskSpec) GetAddCapabilities() []string {
	if x != nil {
		return x.AddCapabilities
	}
	return nil
}

func (x *TaskSpec) GetSeccompUnconfined() bool {
	if x != nil {
		return x.SeccompUnconfined
	}
	return false
}

func (x *TaskSpec) GetReadonlyRootfs() bool {
	if x != nil {
		return x.ReadonlyRootfs
	}
	return false
}

type SecretsBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretsBundle) Reset() {
	*x = SecretsBundle{}
	mi := &file_krayt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretsBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretsBundle) ProtoMessage() {}

func (x *SecretsBundle) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretsBundle.ProtoReflect.Descriptor instead.
func (*SecretsBundle) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{6}
}

func (x *SecretsBundle) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type NetworkPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          NetworkPolicy_Mode     `protobuf:"varint,1,opt,name=mode,proto3,enum=krayt.v1.NetworkPolicy_Mode" json:"mode,omitempty"`
	Allow         []string               `protobuf:"bytes,2,rep,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicy) Reset() {
	*x = NetworkPolicy{}
	mi := &file_krayt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicy) ProtoMessage() {}

func (x *NetworkPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicy.ProtoReflect.Descriptor instead.
func (*NetworkPolicy) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkPolicy) GetMode() NetworkPolicy_Mode {
	if x != nil {
		return x.Mode
	}
	return NetworkPolicy_ALLOWLIST
}

func (x *NetworkPolicy) GetAllow() []string {
	if x != nil {
		return x.Allow
	}
	return nil
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageRef      string                 `protobuf:"bytes,1,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	TimeoutSecs   uint32                 `protobuf:"varint,2,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_krayt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{8}
}

func (x *StartRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *StartRequest) GetTimeoutSecs() uint32 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

type RunEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*RunEvent_Log
	//	*RunEvent_Status
	//	*RunEvent_Question
	//	*RunEvent_Resolved
	Kind          isRunEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEvent) Reset() {
	*x = RunEvent{}
	mi := &file_krayt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEvent) ProtoMessage() {}

func (x *RunEvent) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEvent.ProtoReflect.Descriptor instead.
func (*RunEvent) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{9}
}

func (x *RunEvent) GetKind() isRunEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RunEvent) GetLog() *LogLine {
	if x != nil {
		if x, ok := x.Kind.(*RunEvent_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *RunEvent) GetStatus() *Status {
	if x != nil {
		if x, ok := x.Kind.(*RunEvent_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *RunEvent) GetQuestion() *Question {
	if x != nil {
		if x, ok := x.Kind.(*RunEvent_Question); ok {
			return x.Question
		}
	}
	return nil
}

func (x *RunEvent) GetResolved() *Resolved {
	if x != nil {
		if x, ok := x.Kind.(*RunEvent_Resolved); ok {
			return x.Resolved
		}
	}
	return nil
}

type isRunEvent_Kind interface {
	isRunEvent_Kind()
}

type RunEvent_Log struct {
	Log *LogLine `protobuf:"bytes,1,opt,name=log,proto3,oneof"`
}

type RunEvent_Status struct {
	Status *Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"` // terminal; last message on the stream
}

type RunEvent_Question struct {
	Question *Question `protobuf:"bytes,3,opt,name=question,proto3,oneof"` // agent paused to ask the human (§6.13); not terminal
}

type RunEvent_Resolved struct {
	Resolved *Resolved `protobuf:"bytes,4,opt,name=resolved,proto3,oneof"` // a question was answered (§6.13); host flips waiting→running
}

func (*RunEvent_Log) isRunEvent_Kind() {}

func (*RunEvent_Status) isRunEvent_Kind() {}

func (*RunEvent_Question) isRunEvent_Kind() {}

func (*RunEvent_Resolved) isRunEvent_Kind() {}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        LogLine_Stream         `protobuf:"varint,1,opt,name=stream,proto3,enum=krayt.v1.LogLine_Stream" json:"stream,omitempty"`
	Line          []byte                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	TsUnixMs      int64                  `protobuf:"varint,3,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_krayt_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{10}
}

func (x *LogLine) GetStream() LogLine_Stream {
	if x != nil {
		return x.Stream
	}
	return LogLine_STDOUT
}

func (x *LogLine) GetLine() []byte {
	if x != nil {
		return x.Line
	}
	return nil
}

func (x *LogLine) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	TimedOut      bool                   `protobuf:"varint,2,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_krayt_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{11}
}

func (x *Status) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Status) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *Status) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Agent → human question (§6.13). Pushed on the Start stream; host replies via Answer().
type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Choices       []string               `protobuf:"bytes,3,rep,name=choices,proto3" json:"choices,omitempty"`
	TimeoutSecs   uint32                 `protobuf:"varint,4,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_krayt_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{12}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Question) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *Question) GetTimeoutSecs() uint32 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

type AnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	NoAnswer      bool                   `protobuf:"varint,3,opt,name=no_answer,json=noAnswer,proto3" json:"no_answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerRequest) Reset() {
	*x = AnswerRequest{}
	mi := &file_krayt_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerRequest) ProtoMessage() {}

func (x *AnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerRequest.ProtoReflect.Descriptor instead.
func (*AnswerRequest) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{13}
}

func (x *AnswerRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *AnswerRequest) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *AnswerRequest) GetNoAnswer() bool {
	if x != nil {
		return x.NoAnswer
	}
	return false
}

// A pending Question was answered — the host called Answer, the timeout sentinel fired, or a
// separate `krayt answer` process dialed the guest — so the agent's ask_human call returned. The
// guest emits it when bridge.Answer delivers; the host flips the run waiting→running precisely,
// independent of who answered (§6.13).
type Resolved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resolved) Reset() {
	*x = Resolved{}
	mi := &file_krayt_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resolved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resolved) ProtoMessage() {}

func (x *Resolved) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resolved.ProtoReflect.Descriptor instead.
func (*Resolved) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{14}
}

func (x *Resolved) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

type CollectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectRequest) Reset() {
	*x = CollectRequest{}
	mi := &file_krayt_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRequest) ProtoMessage() {}

func (x *CollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRequest.ProtoReflect.Descriptor instead.
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{15}
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_krayt_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{16}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_krayt_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_krayt_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_krayt_proto_rawDescGZIP(), []int{17}
}

var File_krayt_proto protoreflect.FileDescriptor

const file_krayt_proto_rawDesc = "" +
	"\n" +
	"\vkrayt.proto\x12\bkrayt.v1\"5\n" +
	"\fHelloRequest\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\"c\n" +
	"\rHelloResponse\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12-\n" +
	"\x12containerd_version\x18\x02 \x01(\tR\x11containerdVersion\"%\n" +
	"\tBlobQuery\x12\x18\n" +
	"\adigests\x18\x01 \x03(\tR\adigests\"7\n" +
	"\fBlobPresence\x12'\n" +
	"\x0fmissing_digests\x18\x01 \x03(\tR\x0emissingDigests\"G\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04last\"\x8c\x02\n" +
	"\bTaskSpec\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\fR\x06prompt\x12-\n" +
	"\x03env\x18\x02 \x03(\v2\x1b.krayt.v1.TaskSpec.EnvEntryR\x03env\x12)\n" +
	"\x10add_capabilities\x18\x03 \x03(\tR\x0faddCapabilities\x12-\n" +
	"\x12seccomp_unconfined\x18\x04 \x01(\bR\x11seccompUnconfined\x12'\n" +
	"\x0freadonly_rootfs\x18\x05 \x01(\bR\x0ereadonlyRootfs\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\rSecretsBundle\x12;\n" +
	"\x06values\x18\x01 \x03(\v2#.krayt.v1.SecretsBundle.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\rNetworkPolicy\x120\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1c.krayt.v1.NetworkPolicy.ModeR\x04mode\x12\x14\n" +
	"\x05allow\x18\x02 \x03(\tR\x05allow\")\n" +
	"\x04Mode\x12\r\n" +
	"\tALLOWLIST\x10\x00\x12\b\n" +
	"\x04FULL\x10\x01\x12\b\n" +
	"\x04NONE\x10\x02\"N\n" +
	"\fStartRequest\x12\x1b\n" +
	"\timage_ref\x18\x01 \x01(\tR\bimageRef\x12!\n" +
	"\ftimeout_secs\x18\x02 \x01(\rR\vtimeoutSecs\"\xc9\x01\n" +
	"\bRunEvent\x12%\n" +
	"\x03log\x18\x01 \x01(\v2\x11.krayt.v1.LogLineH\x00R\x03log\x12*\n" +
	"\x06status\x18\x02 \x01(\v2\x10.krayt.v1.StatusH\x00R\x06status\x120\n" +
	"\bquestion\x18\x03 \x01(\v2\x12.krayt.v1.QuestionH\x00R\bquestion\x120\n" +
	"\bresolved\x18\x04 \x01(\v2\x12.krayt.v1.ResolvedH\x00R\bresolvedB\x06\n" +
	"\x04kind\"\x8f\x01\n" +
	"\aLogLine\x120\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x18.krayt.v1.LogLine.StreamR\x06stream\x12\x12\n" +
	"\x04line\x18\x02 \x01(\fR\x04line\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x03 \x01(\x03R\btsUnixMs\" \n" +
	"\x06Stream\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\"X\n" +
	"\x06Status\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x1b\n" +
	"\ttimed_out\x18\x02 \x01(\bR\btimedOut\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"o\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x18\n" +
	"\achoices\x18\x03 \x03(\tR\achoices\x12!\n" +
	"\ftimeout_secs\x18\x04 \x01(\rR\vtimeoutSecs\"i\n" +
	"\rAnswerRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\x12\x1b\n" +
	"\tno_answer\x18\x03 \x01(\bR\bnoAnswer\"+\n" +
	"\bResolved\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\"\x10\n" +
	"\x0eCollectRequest\"+\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x11\n" +
	"\x0fShutdownRequest2\xe5\x04\n" +
	"\n" +
	"GuestAgent\x128\n" +
	"\x05Hello\x12\x16.krayt.v1.HelloRequest\x1a\x17.krayt.v1.HelloResponse\x12>\n" +
	"\x0fQueryImageBlobs\x12\x13.krayt.v1.BlobQuery\x1a\x16.krayt.v1.BlobPresence\x12-\n" +
	"\tPushImage\x12\x0f.krayt.v1.Chunk\x1a\r.krayt.v1.Ack(\x01\x12,\n" +
	"\bPushCode\x12\x0f.krayt.v1.Chunk\x1a\r.krayt.v1.Ack(\x01\x12-\n" +
	"\bPushTask\x12\x12.krayt.v1.TaskSpec\x1a\r.krayt.v1.Ack\x125\n" +
	"\vPushSecrets\x12\x17.krayt.v1.SecretsBundle\x1a\r.krayt.v1.Ack\x12:\n" +
	"\x10SetNetworkPolicy\x12\x17.krayt.v1.NetworkPolicy\x1a\r.krayt.v1.Ack\x125\n" +
	"\x05Start\x12\x16.krayt.v1.StartRequest\x1a\x12.krayt.v1.RunEvent0\x01\x12?\n" +
	"\x10CollectArtifacts\x12\x18.krayt.v1.CollectRequest\x1a\x0f.krayt.v1.Chunk0\x01\x120\n" +
	"\x06Answer\x12\x17.krayt.v1.AnswerRequest\x1a\r.krayt.v1.Ack\x124\n" +
	"\bShutdown\x12\x19.krayt.v1.ShutdownRequest\x1a\r.krayt.v1.AckB1Z/github.com/418-cloud/krayt/internal/protocol/pbb\x06proto3"

var (
	file_krayt_proto_rawDescOnce sync.Once
	file_krayt_proto_rawDescData []byte
)

func file_krayt_proto_rawDescGZIP() []byte {
	file_krayt_proto_rawDescOnce.Do(func() {
		file_krayt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_krayt_proto_rawDesc), len(file_krayt_proto_rawDesc)))
	})
	return file_krayt_proto_rawDescData
}

var file_krayt_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_krayt_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_krayt_proto_goTypes = []any{
	(NetworkPolicy_Mode)(0), // 0: krayt.v1.NetworkPolicy.Mode
	(LogLine_Stream)(0),     // 1: krayt.v1.LogLine.Stream
	(*HelloRequest)(nil),    // 2: krayt.v1.HelloRequest
	(*HelloResponse)(nil),   // 3: krayt.v1.HelloResponse
	(*BlobQuery)(nil),       // 4: krayt.v1.BlobQuery
	(*BlobPresence)(nil),    // 5: krayt.v1.BlobPresence
	(*Chunk)(nil),           // 6: krayt.v1.Chunk
	(*TaskSpec)(nil),        // 7: krayt.v1.TaskSpec
	(*SecretsBundle)(nil),   // 8: krayt.v1.SecretsBundle
	(*NetworkPolicy)(nil),   // 9: krayt.v1.NetworkPolicy
	(*StartRequest)(nil),    // 10: krayt.v1.StartRequest
	(*RunEvent)(nil),        // 11: krayt.v1.RunEvent
	(*LogLine)(nil),         // 12: krayt.v1.LogLine
	(*Status)(nil),          // 13: krayt.v1.Status
	(*Question)(nil),        // 14: krayt.v1.Question
	(*AnswerRequest)(nil),   // 15: krayt.v1.AnswerRequest
	(*Resolved)(nil),        // 16: krayt.v1.Resolved
	(*CollectRequest)(nil),  // 17: krayt.v1.CollectRequest
	(*Ack)(nil),             // 18: krayt.v1.Ack
	(*ShutdownRequest)(nil), // 19: krayt.v1.ShutdownRequest
	nil,                     // 20: krayt.v1.TaskSpec.EnvEntry
	nil,                     // 21: krayt.v1.SecretsBundle.ValuesEntry
}
var file_krayt_proto_depIdxs = []int32{
	20, // 0: krayt.v1.TaskSpec.env:type_name -> krayt.v1.TaskSpec.EnvEntry
	21, // 1: krayt.v1.SecretsBundle.values:type_name -> krayt.v1.SecretsBundle.ValuesEntry
	0,  // 2: krayt.v1.NetworkPolicy.mode:type_name -> krayt.v1.NetworkPolicy.Mode
	12, // 3: krayt.v1.RunEvent.log:type_name -> krayt.v1.LogLine
	13, // 4: krayt.v1.RunEvent.status:type_name -> krayt.v1.Status
	14, // 5: krayt.v1.RunEvent.question:type_name -> krayt.v1.Question
	16, // 6: krayt.v1.RunEvent.resolved:type_name -> krayt.v1.Resolved
	1,  // 7: krayt.v1.LogLine.stream:type_name -> krayt.v1.LogLine.Stream
	2,  // 8: krayt.v1.GuestAgent.Hello:input_type -> krayt.v1.HelloRequest
	4,  // 9: krayt.v1.GuestAgent.QueryImageBlobs:input_type -> krayt.v1.BlobQuery
	6,  // 10: krayt.v1.GuestAgent.PushImage:input_type -> krayt.v1.Chunk
	6,  // 11: krayt.v1.GuestAgent.PushCode:input_type -> krayt.v1.Chunk
	7,  // 12: krayt.v1.GuestAgent.PushTask:input_type -> krayt.v1.TaskSpec
	8,  // 13: krayt.v1.GuestAgent.PushSecrets:input_type -> krayt.v1.SecretsBundle
	9,  // 14: krayt.v1.GuestAgent.SetNetworkPolicy:input_type -> krayt.v1.NetworkPolicy
	10, // 15: krayt.v1.GuestAgent.Start:input_type -> krayt.v1.StartRequest
	17, // 16: krayt.v1.GuestAgent.CollectArtifacts:input_type -> krayt.v1.CollectRequest
	15, // 17: krayt.v1.GuestAgent.Answer:input_type -> krayt.v1.AnswerRequest
	19, // 18: krayt.v1.GuestAgent.Shutdown:input_type -> krayt.v1.ShutdownRequest
	3,  // 19: krayt.v1.GuestAgent.Hello:output_type -> krayt.v1.HelloResponse
	5,  // 20: krayt.v1.GuestAgent.QueryImageBlobs:output_type -> krayt.v1.BlobPresence
	18, // 21: krayt.v1.GuestAgent.PushImage:output_type -> krayt.v1.Ack
	18, // 22: krayt.v1.GuestAgent.PushCode:output_type -> krayt.v1.Ack
	18, // 23: krayt.v1.GuestAgent.PushTask:output_type -> krayt.v1.Ack
	18, // 24: krayt.v1.GuestAgent.PushSecrets:output_type -> krayt.v1.Ack
	18, // 25: krayt.v1.GuestAgent.SetNetworkPolicy:output_type -> krayt.v1.Ack
	11, // 26: krayt.v1.GuestAgent.Start:output_type -> krayt.v1.RunEvent
	6,  // 27: krayt.v1.GuestAgent.CollectArtifacts:output_type -> krayt.v1.Chunk
	18, // 28: krayt.v1.GuestAgent.Answer:output_type -> krayt.v1.Ack
	18, // 29: krayt.v1.GuestAgent.Shutdown:output_type -> krayt.v1.Ack
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_krayt_proto_init() }
func file_krayt_proto_init() {
	if File_krayt_proto != nil {
		return
	}
	file_krayt_proto_msgTypes[9].OneofWrappers = []any{
		(*RunEvent_Log)(nil),
		(*RunEvent_Status)(nil),
		(*RunEvent_Question)(nil),
		(*RunEvent_Resolved)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_krayt_proto_rawDesc), len(file_krayt_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_krayt_proto_goTypes,
		DependencyIndexes: file_krayt_proto_depIdxs,
		EnumInfos:         file_krayt_proto_enumTypes,
		MessageInfos:      file_krayt_proto_msgTypes,
	}.Build()
	File_krayt_proto = out.File
	file_krayt_proto_goTypes = nil
	file_krayt_proto_depIdxs = nil
}
